# Generated by Django 6.0.6 on 2026-06-09 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('facility', 'Facility'), ('equipment', 'Equipment'), ('classes', 'Classes'), ('transformation', 'Transformations'), ('events', 'Events')], default='facility', max_length=30)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('contact', 'Contact Form'), ('simulator', 'Fitness Simulator'), ('membership', 'Membership Inquiry')], default='contact', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fitness_level', models.CharField(blank=True, max_length=50)),
                ('fitness_goal', models.CharField(blank=True, max_length=50)),
                ('timeline', models.CharField(blank=True, max_length=50)),
                ('recommended_plan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='trainers/')),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('specialties', models.CharField(max_length=255)),
                ('certifications', models.TextField()),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('before_photo', models.ImageField(blank=True, upload_to='transformations/')),
                ('after_photo', models.ImageField(blank=True, upload_to='transformations/')),
                ('duration', models.CharField(max_length=50)),
                ('weight_lost', models.CharField(blank=True, max_length=30)),
                ('muscle_gained', models.CharField(blank=True, max_length=30)),
                ('testimonial', models.TextField()),
                ('goal_type', models.CharField(default='Weight Loss', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
